using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Tuto.Publishing
{
	public class ULearnVideoCommands : VideoCommandBlockModel<ULearnSource, ULearnLectureCommands>
	{
		public ULearnVideoCommands(ULearnSource source, VideoWrap wrap)
			: base(source, wrap)
		{
			Commands.Add(new VisualCommand(Compile, () => true, "compile.png"));
            Commands.Add(new VisualCommand(() => Process.Start("\"" + Source.FileForSlide(Wrap).FullName + "\""), () => true, "view.png"));
        }



        string CreateContent(string entry)
        {
            var template = @"
//automatically generated by Tuto
namespace {0} 
{{
    Slide[@""{1}"",""{2}""]
    public class {3}
        {{
{4}
        }}
}}";

            return string.Format(template,
                Source.Settings.CourseAbbreviation,
                Wrap.Caption,
                Wrap.Guid,
                Source.CSConvert(Wrap.Caption),
                entry);
        }

        string CreateVideoEntry()
        {
            var clip =  Wrap.BlockOfType<YoutubeVideoCommands>().YoutubeClip;
            if (clip != null) return string.Format("\t\t//#video " + clip.Id);
            return "";
        }

        string PrepareGalleryAndCreateEntry()
        {
            var latexBlock = Wrap.BlockOfType<LatexVideoCommands>();
            if (latexBlock.Status.Status != Statuses.OK) return "";
            var sourceDirectory = latexBlock.DueSlidesDirectory;
            string galleryName = string.Format("{0:D2}-files", Wrap.NumberInTopic);
            var dstDirectory = new DirectoryInfo(Path.Combine(Source.FileForSlide(Wrap).Directory.FullName, galleryName));
            if (dstDirectory.Exists) dstDirectory.Delete(true);
            dstDirectory.Create();
            foreach (var file in sourceDirectory.GetFiles())
                file.CopyTo(Path.Combine(dstDirectory.FullName, file.Name));
            return "\t\t//#gallery " + galleryName;

        }

        public void Compile()
        {
            if (!Source.FileForSlide(Wrap).Directory.Exists) Source.FileForSlide(Wrap).Directory.Create();
            var content = CreateContent(CreateVideoEntry()+"\n"+PrepareGalleryAndCreateEntry());
            System.IO.File.WriteAllText(Source.FileForSlide(Wrap).FullName, content);
        }

       

		public override string ImageFileName
		{
			get { return "ULearn.png"; }
		}

		public override BlockStatus Status
		{
			get { return BlockStatus.No(); }
		}
	}
}
