using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Tuto.Publishing
{
	public class ULearnVideoCommands : VideoCommandBlockModel<ULearnSource, ULearnLectureCommands>
	{
		public ULearnVideoCommands(ULearnSource source, VideoWrap wrap)
			: base(source, wrap)
		{
			Commands.Add(new VisualCommand(Compile, () => true, "compile.png"));
            File = new FileInfo(Path.Combine(LectureData.Directory.FullName, string.Format("S{0:D2} - {1}", Wrap.NumberInTopic, Wrap.Caption)));
        }

        string CreateContent(string entry)
        {
            var template = @"
//automatically generated by Tuto
namespace {0} 
{{
    Slide[@""{1}"",""{2}""]
    public class {3}
        {{
        {4}
        }}
}}";

            return string.Format(template,
                Source.Settings.CourseAbbreviation,
                Wrap.Caption,
                Wrap.Guid,
                Source.CSConvert(Wrap.Caption));
        }

        string CreateVideoEntry()
        {
            var clip =  Wrap.BlockOfType<YoutubeVideoCommands>().YoutubeClip;
            if (clip != null) return string.Format("//#video " + clip.Id);
            return "";
        }

        public void Compile()
        {
            if (!File.Directory.Exists) File.Directory.Create();
            var content = CreateContent(CreateVideoEntry());
            System.IO.File.WriteAllText(File.FullName, content);
        }

        FileInfo File;

		public override string ImageFileName
		{
			get { return "ULearn.png"; }
		}

		public override BlockStatus Status
		{
			get { return BlockStatus.No(); }
		}
	}
}
